### PR TITLE
[added]: new Footer component

### PR DESCRIPTION
**Pull request by theakash04**
### added new footer component 
Screenshot from 2024-08-08 23-34-05

### CODE REVIEW

**Comment by theakash04** [comment]
Changes were made to the UI design.

**Comment by anubhavgh023** [comment]
> Changes were made to the UI design.

bit-project-fixes-2


- - Fix the ui.
1. Add github & email icons
2. fix the title alignment
3. fix the sidebar alignment
4. add bit-mesra logo

**Comment by theakash04** [comment]
FIxed:
1. Added github & email icons
2. fixed the title alignment
3. fixed the sidebar alignment
4. added bit-mesra logo

**Comment by anubhavgh023** [comment]
> FIxed:
> 
> 1. Added github & email icons
> 2. fixed the title alignment
> 3. fixed the sidebar alignment
> 4. added bit-mesra logo

- Fix the title alignment
- Make the contributors text small

pr-3

**Comment by theakash04** [comment]
- Fixed the title alignment
- Changed the contributors text small

**Pull request merged**
